// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wakhauampgorhiqklyaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indha2hhdWFtcGdvcmhpcWtseWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTE4NDMsImV4cCI6MjA1ODY2Nzg0M30.dlb9YEoVuNryAw1HDWMnws-i7ilQaMiyEYf6RYit4F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);